### PR TITLE
CSS fixes

### PR DESCRIPTION
**Pull request by Bobby-Finch**
rustyspoke

### CODE REVIEW

**Comment by Bobby-Finch** [comment]
A lot of the changes in the diff are from prettier auto formatting.

**Review by FrankieMarie — APPROVED** [review]

**Review by davetapley — CHANGES_REQUESTED** [review]
Looks great 😎 

I'm a big fan of prettier, but one request: can you check in [the configuration file](https://prettier.io/docs/en/configuration.html)?
Even if it's the default it helps to be consistent in future, and will remind others to use it.

I have no preference on which file you put it in.

Thanks!

**Comment by Bobby-Finch** [comment]
@davetapley 
I was using the VS code extension for Prettier, do you want me to install it via npm? I could also revert the prettier changes if that would be better.

**Comment by davetapley** [comment]
@Bobby-Finch gotcha.
Looks like [the extension uses the same config files](https://github.com/prettier/prettier-vscode?tab=readme-ov-file#configuration), so should be good to check in an empty `.prettierrc` file.

**Pull request merged**
